# Generated by Django 4.1.5 on 2023-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=1000)),
                ('message_received', models.CharField(max_length=1000)),
                ('contact_number', models.IntegerField()),
                ('reply_to', models.EmailField(max_length=254)),
            ],
        ),
    ]
