# Generated by Django 4.1.5 on 2023-03-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_country_alter_order_membership_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='membership_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
