# Generated by Django 4.1.5 on 2023-02-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_remaining',
        ),
    ]
